# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 1

image:
  repository: chedjou03/cards
  tag: latest

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
